FROM mwaeckerlin/very-base AS build
RUN apk add --no-cache curl \
    && LATEST=$(curl -sI https://github.com/the-djmaze/snappymail/releases/latest | sed -n 's|.*location:.*/tag/v\([^[:space:]]*\).*|\1|p') \
    && curl -fsSL "https://github.com/the-djmaze/snappymail/releases/download/v${LATEST}/snappymail-${LATEST}.tar.gz" -o /tmp/snappymail.tar.gz \
    && mkdir /app \
    && tar xf /tmp/snappymail.tar.gz -C /app \
    && rm /tmp/snappymail.tar.gz
RUN $ALLOW_USER /app/data

FROM mwaeckerlin/php-fpm AS php-fpm
COPY --from=build /app /app
VOLUME /app/data
