version: "3.4"
services:
  rainloop-proxy:
    image: mwaeckerlin/rainloop:nginx
    build:
      context: .
      target: nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    networks:
      - frontend
  rainloop:
    image: mwaeckerlin/rainloop:php-fpm
    build:
      context: .
      target: php-fpm
      dockerfile: Dockerfile.php-fpm
    volumes:
      - type: volume
        source: settings
        target: /etc/rainloop
      - type: volume
        source: data
        target: /var/lib/rainloop
    networks:
      - frontend
      - backend
  mysql:
    image: mariadb
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "rainloop"
      MYSQL_USER: "rainloop"
      MYSQL_PASSWORD: "Ch4ng3-7h1S-Pa5SW0rd"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  settings:
  data:
  mysql: