FROM mwaeckerlin/very-base AS build
ADD --chmod=644 https://github.com/the-djmaze/snappymail/releases/latest/download/snappymail.tar.gz /tmp/snappymail.tar.gz
RUN mkdir /app \
    && tar xf /tmp/snappymail.tar.gz -C /app \
    && rm /tmp/snappymail.tar.gz

FROM mwaeckerlin/nginx
ENV PHP_FPM_HOST "snappymail"
COPY --from=build /app /app
