FROM mwaeckerlin/very-base AS build
ADD --chmod=644 https://github.com/the-djmaze/snappymail/releases/latest/download/snappymail.tar.gz /tmp/snappymail.tar.gz
RUN mkdir /app \
    && tar xf /tmp/snappymail.tar.gz -C /app \
    && rm /tmp/snappymail.tar.gz
RUN $ALLOW_USER /app/snappymail/data

FROM mwaeckerlin/php-fpm AS php-fpm
COPY --from=build /app /app
VOLUME /app/snappymail/data
