services:
  snappymail-proxy:
    image: mwaeckerlin/snappymail:nginx
    build:
      context: .
      target: nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    networks:
      - frontend

  snappymail:
    image: mwaeckerlin/snappymail:php-fpm
    build:
      context: .
      target: php-fpm
      dockerfile: Dockerfile.php-fpm
    volumes:
      - type: volume
        source: data
        target: /app/snappymail/data
    networks:
      - frontend
      - backend

  mysql:
    image: mariadb
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "snappymail"
      MYSQL_USER: "snappymail"
      MYSQL_PASSWORD: "Ch4ng3-7h1S-Pa5SW0rd"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  data:
  mysql:
